package life.majiang.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.ID
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TITLE
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMT_CREATE
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMT_MODIFY
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.CREATOR
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.COMMENT_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Integer commentCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.VIEW_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Integer viewCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.LIKE_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private Integer likeCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TAG
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DESCRIPTION
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.ID
     *
     * @return the value of QUESTION.ID
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.ID
     *
     * @param id the value for QUESTION.ID
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.TITLE
     *
     * @return the value of QUESTION.TITLE
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.TITLE
     *
     * @param title the value for QUESTION.TITLE
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.GMT_CREATE
     *
     * @return the value of QUESTION.GMT_CREATE
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.GMT_CREATE
     *
     * @param gmtCreate the value for QUESTION.GMT_CREATE
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.GMT_MODIFY
     *
     * @return the value of QUESTION.GMT_MODIFY
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.GMT_MODIFY
     *
     * @param gmtModify the value for QUESTION.GMT_MODIFY
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.CREATOR
     *
     * @return the value of QUESTION.CREATOR
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.CREATOR
     *
     * @param creator the value for QUESTION.CREATOR
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.COMMENT_COUNTER
     *
     * @return the value of QUESTION.COMMENT_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Integer getCommentCounter() {
        return commentCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.COMMENT_COUNTER
     *
     * @param commentCounter the value for QUESTION.COMMENT_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setCommentCounter(Integer commentCounter) {
        this.commentCounter = commentCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.VIEW_COUNTER
     *
     * @return the value of QUESTION.VIEW_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Integer getViewCounter() {
        return viewCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.VIEW_COUNTER
     *
     * @param viewCounter the value for QUESTION.VIEW_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setViewCounter(Integer viewCounter) {
        this.viewCounter = viewCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.LIKE_COUNTER
     *
     * @return the value of QUESTION.LIKE_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public Integer getLikeCounter() {
        return likeCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.LIKE_COUNTER
     *
     * @param likeCounter the value for QUESTION.LIKE_COUNTER
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setLikeCounter(Integer likeCounter) {
        this.likeCounter = likeCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.TAG
     *
     * @return the value of QUESTION.TAG
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.TAG
     *
     * @param tag the value for QUESTION.TAG
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.DESCRIPTION
     *
     * @return the value of QUESTION.DESCRIPTION
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.DESCRIPTION
     *
     * @param description the value for QUESTION.DESCRIPTION
     *
     * @mbg.generated Fri Jun 12 10:35:29 PDT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}